### ISSUE TITLE
OMS Linux Agent not working on RHEL 8.2

### ISSUE THREAD

**Issue by GhanshamMahajan** [microsoft/OMS-Agent-for-Linux#1217]
**OS :** Red Hat Enterprise Linux release 8.2 (Ootpa)

**Kernel :** Linux VMNanem 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Mon Jun 1 20:24:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

OMSAgent Version : omsagent-1.13.7-0.universal.x64.sh

**Error :** 
Checking host architecture ...
**Error: Python is not configured or Python does not support ctypes on this system, installation cannot continue.**
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61

**Comment by bhsanghv** [comment]
I receive the same error on RHEL 8.2, centos 8.1.1911, SUSE ( sles 15.1)

Checking host architecture ...
Error: Python is not configured or Python does not support ctypes on this system, installation cannot continue.
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61

**Comment by ranieuwe** [comment]
related to #1216 this is due to a change in Python on RHEL8.2 and Ubuntu 20.04 LTS.

**Comment by hestolz** [comment]
Hi all, new release 1.13.27 now supports RHEL8.X, SLES 15.X, Ubuntu 20.04, and has no python2/3 aliasing requirements. You'll still need `python-ctypes` regardless of which python version you chose, but the other issues should be resolved. The extension is deployed to all public regions and available here on GitHub as well.

**Comment by GhanshamMahajan** [comment]
This is still not running on CentOS 8 and RHEL 8.

I try to run and it's given error : "**Shell bundle exiting with code 18**"

You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

Shell bundle exiting with code 18

I run the troubleshooter and it's clearly mentioned that "ERROR FOUND: This version of Red Hat Enterprise Linux (8.3) is not supported."

`================================================================================
CHECKING HEARTBEAT / HEALTH...
Checking if installed correctly...
ERROR FOUND: OMSConfig isn't installed correctly.
ERROR(S) FOUND.
ERROR FOUND: OMS isn't installed correctly.
ERROR(S) FOUND.
Running the installation part of the troubleshooter in order to find the issue...
==============================================================================
CHECKING INSTALLATION...
Checking if running a supported OS version...
ERROR(S) FOUND.
==============================================================================
==============================================================================
ALL ERRORS/WARNINGS ENCOUNTERED:
  ERROR FOUND: OMSConfig isn't installed correctly.
--------------------------------------------------------------------------------
  ERROR FOUND: OMS isn't installed correctly.
--------------------------------------------------------------------------------
  ERROR FOUND: This version of Red Hat Enterprise Linux (8.3) is not supported. Please download 6 or 7. To see all supported Operating Systems, please go to:

   https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#supported-linux-operating-systems

--------------------------------------------------------------------------------
Please review the errors found above.
 Do you want to run another scenario? (y/n): n
`

When we expect the solutions on this.
