### ISSUE TITLE
CentOS 7 - dozens of processes in Update management enabled solution

### ISSUE THREAD

**Issue by silverl** [Microsoft/OMS-Agent-for-Linux#511]
CentOS Linux release 7.3.1611
omsagent-1.3.5-127.universal.x64

After some time, perhaps a day, load is high and I have 146 processes in the process table with "omsagent" in their string.
```
# ps -ef | grep oms | wc -l
146
```

Many of the processes look like this:
```
omsagent 47377 47371  0 15:30 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 47379 47377  0 15:30 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 48602 48599  0 15:35 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 48604 48602  0 15:35 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 49838 49831  0 15:40 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 49841 49838  0 15:40 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 51089 51085  0 15:45 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 51091 51089  0 15:45 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 52318 52311  0 15:50 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 52320 52318  0 15:50 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 53538 53533  0 15:55 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 53539 53538  0 15:55 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 54767 54761  0 16:00 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 54769 54767  0 16:00 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 56032 56028  0 16:05 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
```

I restart the service, and they're back the next day, choking the server.

Any ideas?

**Comment by silverl** [comment]
```
# systemctl | grep oms
  session-1301.scope                                                                                                      loaded active running   Session 1301 of user omsagent
  session-1304.scope                                                                                                      loaded active running   Session 1304 of user omsagent
  session-1306.scope                                                                                                      loaded active running   Session 1306 of user omsagent
  session-1311.scope                                                                                                      loaded active running   Session 1311 of user omsagent
  session-1313.scope                                                                                                      loaded active running   Session 1313 of user omsagent
  session-1316.scope                                                                                                      loaded active running   Session 1316 of user omsagent
  session-1317.scope                                                                                                      loaded active running   Session 1317 of user omsagent
  session-1321.scope                                                                                                      loaded active running   Session 1321 of user omsagent
  session-1323.scope                                                                                                      loaded active running   Session 1323 of user omsagent
  session-1325.scope                                                                                                      loaded active running   Session 1325 of user omsagent
  session-1328.scope                                                                                                      loaded active running   Session 1328 of user omsagent
  session-1330.scope                                                                                                      loaded active running   Session 1330 of user omsagent
  session-1333.scope                                                                                                      loaded active running   Session 1333 of user omsagent
  session-1336.scope                                                                                                      loaded active running   Session 1336 of user omsagent
  session-1337.scope                                                                                                      loaded active running   Session 1337 of user omsagent
  session-1341.scope                                                                                                      loaded active running   Session 1341 of user omsagent
  session-1343.scope                                                                                                      loaded active running   Session 1343 of user omsagent
  session-1347.scope                                                                                                      loaded active running   Session 1347 of user omsagent
  session-1349.scope                                                                                                      loaded active running   Session 1349 of user omsagent
  session-1352.scope                                                                                                      loaded active running   Session 1352 of user omsagent
  session-1354.scope                                                                                                      loaded active running   Session 1354 of user omsagent
  session-1356.scope                                                                                                      loaded active running   Session 1356 of user omsagent
  session-1360.scope                                                                                                      loaded active running   Session 1360 of user omsagent
  session-1362.scope                                                                                                      loaded active running   Session 1362 of user omsagent
  session-1365.scope                                                                                                      loaded active running   Session 1365 of user omsagent
  session-1367.scope                                                                                                      loaded active running   Session 1367 of user omsagent
  session-1369.scope                                                                                                      loaded active running   Session 1369 of user omsagent
  session-1372.scope                                                                                                      loaded active running   Session 1372 of user omsagent
  session-1375.scope                                                                                                      loaded active running   Session 1375 of user omsagent
  session-1377.scope                                                                                                      loaded active running   Session 1377 of user omsagent
  session-1381.scope                                                                                                      loaded active running   Session 1381 of user omsagent
  session-1383.scope                                                                                                      loaded active running   Session 1383 of user omsagent
  session-1386.scope                                                                                                      loaded active running   Session 1386 of user omsagent
  session-1388.scope                                                                                                      loaded active running   Session 1388 of user omsagent
  session-1391.scope                                                                                                      loaded active running   Session 1391 of user omsagent
  session-1393.scope                                                                                                      loaded active running   Session 1393 of user omsagent
  session-1394.scope                                                                                                      loaded active running   Session 1394 of user omsagent
  session-1398.scope                                                                                                      loaded active running   Session 1398 of user omsagent
  session-1399.scope                                                                                                      loaded active running   Session 1399 of user omsagent
  session-1403.scope                                                                                                      loaded active running   Session 1403 of user omsagent
  session-1405.scope                                                                                                      loaded active running   Session 1405 of user omsagent
  session-1408.scope                                                                                                      loaded active running   Session 1408 of user omsagent
  session-1412.scope                                                                                                      loaded active running   Session 1412 of user omsagent
  session-1414.scope                                                                                                      loaded active running   Session 1414 of user omsagent
  session-1416.scope                                                                                                      loaded active running   Session 1416 of user omsagent
  session-1419.scope                                                                                                      loaded active running   Session 1419 of user omsagent
  session-1420.scope                                                                                                      loaded active running   Session 1420 of user omsagent
  session-1424.scope                                                                                                      loaded active running   Session 1424 of user omsagent
  session-1425.scope                                                                                                      loaded active running   Session 1425 of user omsagent
  session-1428.scope                                                                                                      loaded active running   Session 1428 of user omsagent
  session-1430.scope                                                                                                      loaded active running   Session 1430 of user omsagent
  session-1435.scope                                                                                                      loaded active running   Session 1435 of user omsagent
  session-1437.scope                                                                                                      loaded active running   Session 1437 of user omsagent
  session-1440.scope                                                                                                      loaded active running   Session 1440 of user omsagent
  session-1441.scope                                                                                                      loaded active running   Session 1441 of user omsagent
  session-1445.scope                                                                                                      loaded active running   Session 1445 of user omsagent
  session-1447.scope                                                                                                      loaded active running   Session 1447 of user omsagent
  session-1449.scope                                                                                                      loaded active running   Session 1449 of user omsagent
  session-1452.scope                                                                                                      loaded active running   Session 1452 of user omsagent
  session-1456.scope                                                                                                      loaded active running   Session 1456 of user omsagent
  omsagent-4c86f615-b55c-4de2-915b-bd836749ee3a.service                                                                   loaded active running   Operations Management Suite agent
```

**Comment by lagalbra** [comment]
@silverl We are aware of this issue, and are working on a fix.
@Atchub @NarineM Can you give an ETA for the fix for this?

**Comment by silverl** [comment]
Even if there's a temporary workaround, please let me know. Thanks.

**Comment by silverl** [comment]
Checking back after a week. Is there any suggested workaround? Should I just set up a cron job to kill these processes and restart omsagent?

**Comment by silverl** [comment]
After a little more investigation, I can see that the proliferation of jobs is being caused by a cron.d script. Here's the process tree.

```
/usr/sbin/crond -n
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
 \_ /usr/sbin/CROND -n
 |   \_ /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
 |       \_ /opt/omi/bin/OMSConsistencyInvoker
```

There's a script `/etc/cron.d/OMSConsistencyInvoker` that contains:
```
*/5 * * * * omsagent /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
```
OMSConsistencyInvoker appears to be a binary executable, so I cannot see why it might be failing to exit properly.

**Comment by silverl** [comment]
Your cron job runs OMSConsistencyInvoker every 5 minutes of every day. I wanted to know how long it usually runs for.

I sudo'd to the omsagent user and ran OMSConsistencyInvoker using time:
```
bash-4.2$ time /opt/omi/bin/OMSConsistencyInvoker
```
I thought I might rewrite the cron job using the `timeout` command to force-kill the process after a certain amount of time, after which its work would surely be done.

It ran for longer than 8 minutes, after which I killed it manually.

It provided no output whatsoever.

`OMSConsistencyInvoker` is scheduled to run every 5 minutes, runs longer than 8 minutes (or forever), and is completely opaque producing no discernible output.

I'm going to put the `timeout` command into the cronjob to kill it at 5 minutes. It seems the creator's intent is that it be run every 5 minutes, so I am left to assume it'd be safe to kill at 5 minutes in order to keep my process table clean and my machine from becoming overburdened.

**Comment by silverl** [comment]
For anyone else having this issue, here's my modified `/etc/cron.d/OMSConsistencyInvoker` file:
```
*/5 * * * * omsagent /bin/timeout 5s /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
```

**Comment by NarineM** [comment]
@silverl 
Can you confirm you have update management solution enabled?

**Comment by silverl** [comment]
@NarineM Confirmed, we are running the update management solution.

**Comment by NarineM** [comment]
@silverl 
Thanks, in that case this is a known bug and the fix is in code review right now. The fix would not require you to update omsagent version that you are currently running in your environment . Once the fix is alive, I will let you know.

**Comment by silverl** [comment]
Thank you.

**Comment by roamin9** [comment]
@silverl hi, we encountered the same problem. How about your:
```
service omid status
```

After restart the omid service, OMSConsistencyInvoker works as normal

```
service omid restart
```

**Comment by tony-rothenbacher** [comment]
I'm also facing this same issue with these OMSConsistenceyInvoker processes stacking up and bringing the server to a crawl.

We're running omsagent version 1.3.5-127 x86-64 on CentOS Linux release 7.3.1611.

[maskedUser@maskedHost~]$ rpm -qa | grep oms
omsagent-1.3.5-127.x86_64

[maskedUser@maskedHost~]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

[maskedUser@maskedHost~]$ ps -ef | grep '/bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1' | wc -l
258

omsagent 130242 130238  0 Aug01 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 130243 130242  0 Aug01 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 130414 130410  0 Aug01 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 130415 130414  0 Aug01 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 130584 130581  0 Aug01 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 130586 130584  0 Aug01 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 130756 130753  0 Aug01 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 130759 130756  0 Aug01 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker
omsagent 130979 130975  0 Aug01 ?        00:00:00 /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1
omsagent 130981 130979  0 Aug01 ?        00:00:00 /opt/omi/bin/OMSConsistencyInvoker

**Comment by lagalbra** [comment]
@tony-rothenbacher This issue has been fixed with our latest OMSAgent release, available for download here: https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_GA_v1.4.0-45

Please let us know if removing the old version and re-installing version 1.4.0-45 does not work to resolve the issue.

**Comment by silverl** [comment]
This issue needs to be re-opened. I am running omsagent-1.4.0-45.x86_64 and the issue is still occurring.

**Comment by NarineM** [comment]
@Atchub , @amitsara 
Please take a look. This must be some other use case where ConsistencyInvoker spins up proc numbers which was not fixed by 1.4.0-45 build. Adding omsconfig contact to count this incident as well to consider changing ConsistencyInvoker for long running operations.

@silverl . Thank you for reporting this issue. Can you create a issue on https://github.com/Microsoft/PowerShell-DSC-for-Linux repo and add a link to this page ? This issue is about fixing either omsconfig or resource provider and both of them reside on powershell dsc repo.

**Comment by silverl** [comment]
Confirming that we're definitely still seeing this behavior.

Opened https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues/304

**Comment by LBegnaud** [comment]
What are the implications of adding the timeout for the OMSConsistencyInvoker cron job?

**Comment by silverl** [comment]
If the job got its work done and is simply having trouble exiting, it kills the process.

If the job didn't get its work done, then the implication is that whatever it was intended to do doesn't get done.

**Comment by LBegnaud** [comment]
Do we know the role of the OMSConsistencyInvoker binary?

**Comment by lagalbra** [comment]
The role of the OMSConsistencyInvoker binary is to check that the configuration for the OMSAgent on the machine matches that set by the server. This check is made every 5 minutes.

**Comment by LBegnaud** [comment]
Thanks for the clarification. Seems like it should be fine to kill it if it doesn't exit on its own quickly

**Comment by silverl** [comment]
@NarineM - No action has been taken in the https://github.com/Microsoft/PowerShell-DSC-for-Linux repo. 

After a yum update last night, my cron job fix was replaced with the default and my servers killed themselves within a couple of hours.

**Comment by lagalbra** [comment]
The DSC team has been notified of the issue, and investigations into it are still open.

**Comment by alcohol** [comment]
So.. I guess this isn't really supposed to happen 🤔 

```
$ ps aux | grep /opt/omi/bin/OMSConsistencyInvoker | wc -l
2027
```

**Comment by NarineM** [comment]
The fix is targeted to be available in the next release of omsagent. Stay tuned.

**Comment by marcofl** [comment]
How will that update for "next release" be installed on an existing server?

**Comment by lagalbra** [comment]
If the OMSAgent has been installed on that server through the OmsAgentForLinux Azure VM extension, it will automatically be updated to the next release.

However, if you have manually installed the OMSAgent through [our Quick Install script](https://github.com/Microsoft/OMS-Agent-for-Linux/tree/master#quick-install-guide) or other script, then you will have to download the next version from [our releases page](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) and update it manually.

**Comment by marcofl** [comment]
thank you @lagalbra
